apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: html-pvc
  labels:
    env: html-testing
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: html-log-pvc
  labels:
    env: html-testing
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
