apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-pvc
  labels:
    env: php-testing
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-log-pvc
  labels:
    env: php-testing
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
